### ISSUE TITLE
gpgconf does not always return valid pinentry path

### ISSUE THREAD

**Issue by terinjokes** [gopasspw/pinentry#1]
In https://github.com/gopasspw/gopass/pull/1758, the pinentry package was modified to return the "pinentry" value parsed from the output of `gpgconf`. However, the values returned by `gpgconf` are [defined at compile time](https://github.com/gpg/gnupg/blob/gnupg-2.3.1/common/homedir.c#L1014-L1073). While this may be reasonable for gpg binary itself, it's not always possible to know the correct path to a pinentry implementation at the time gpg is being compiled, so the returned path will not point at a binary.

This is not a problem for gpg, as most users will be using gpg-agent, which will look for "pinentry-program" option from a gpg-agent.conf, and which can also be overridden with the "--pinentry-program" flag.

How do you feel about a pull request with one or more of the following changes?

1. Continue to check `gpgconf` in `GetBinary`, but check to make sure the path exists and is executable before returning it.
2. Add a check for an environment variable in `GetBinary` that allows the user to configure an acceptable pinentry.
3. Modify `New` to allow passing an optional path to a pinentry. The users of the pinentry package could then override the `GetBinary` logic with their own configuration files or command line flags.

---

Up until (relatively) recently `yubikey-agent` was using the pinentry package from gopass predating this change, where the string "pinentry" was returned. This allowed Go to find it on the PATH, which was being configured with the correct pinentry in the `systemd --user` service unit.

I have a temporary workaround by adding a `gpgconf` shell script to the yubikey-agent unit's path that only returns a correct pinentry path. I'd rather have a more official fix.

**Comment by AnomalRoil** [comment]
@dominikschulz What's your take?
On my side I'd welcome a PR doing these. 

The goal of splitting pinentry into its own repo was to be able to better support usecases where it was used in other setup than our, so if these would help with yours, I don't think it would be an issue for us or others. 

We'll just need to be careful around versioning if we introduce breaking changes to the way `New` works
